### ISSUE TITLE
Undefined method with for Model

### ISSUE THREAD

**Issue by leoplct** [GeorgeKaraszi/ActiveRecordExtended#50]
I have added
`gem 'active_record_extended'`
then `bundle` 

but I get this error

```
irb(main):005:0> Profile.with(test: Profile.all)
Traceback (most recent call last):
        1: from (irb):5
NoMethodError (undefined method `with' for #<Class:0x00007fab63c67c88>)
```

```
irb(main):007:0> Profile.public_methods.include?(:with)
=> false
```

What could be the reason?

**Gemfile.lock**
```
active_record_extended (1.4.0)
      activerecord (>= 5.0, < 6.1)
      ar_outer_joins (~> 0.2)
      pg (< 2.0)
```

**config/boot.rb**
```
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)

require 'bundler/setup' # Set up gems listed in the Gemfile.
require 'bootsnap/setup' # Speed up boot time by caching expensive operations.
```
**config/application.rb**

```
require_relative 'boot'
require 'rails/all'
# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)
# CUSTOM
require "active_record_extended"
```
**config/enviroment.rb**
```
# Load the Rails application.
require_relative 'application'
# Initialize the Rails application.
Rails.application.initialize!
```

**Comment by GeorgeKaraszi** [comment]
Which Rail's version are you running?

**Comment by leoplct** [comment]
rails (6.0.3.4)

**Comment by GeorgeKaraszi** [comment]
Are you using classic or Zeitwerk autoloader?

**Comment by leoplct** [comment]
I am not sure about. It's not present in the Gemfile, but i found this in Gemfile.lock
```
activesupport (6.0.3.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
      zeitwerk (~> 2.2, >= 2.2.2)
zeitwerk (2.4.2)
```

**Comment by GeorgeKaraszi** [comment]
If you never went into your `application.rb` file and explicitly set the config to use classic loader, then I got a feeling its the cause of not only your's, but other peoples issues too.

couple of temp fixes you can try until I can address zeitwerk: 

in your `config/application.rb` file, insert this line: `config.autoloader = :classic`

otherwise you can add `require "active_record_extended"` **after** the `require "rails"`

**Comment by leoplct** [comment]
I have tried both options but I got the same error. I have tried to comment all inside "Application" class but it's the same.

I think it's something related to the .with method.

This NOT works -> Profile.with(test: Profile.all)
This works -> Item.where.any(field: 'text')

NoMethodError (undefined method `with' for #<Class:0x00007febc1cc15a0>)

**Comment by GeorgeKaraszi** [comment]
Try replacing the gem with `gem "active_record_extended", git: "https://github.com/GeorgeKaraszi/ActiveRecordExtended.git"` 

I haven't done a new release quite yet. And the current Master branch includes a lot of Rails 6.0 fixes.

**Comment by leoplct** [comment]
Tried. Same error.

**Comment by GeorgeKaraszi** [comment]
It's hard to say tbh... I just created a new Rails 6.0.x project. And all I did was add the gem to the gemfile and its working for me, out of the box.
```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.4'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

gem "active_record_extended", git: "https://github.com/GeorgeKaraszi/ActiveRecordExtended.git"

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '~> 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

```


```
$: rails c
> User.with(test: User.all).to_sql #=> "WITH \"test\" AS (SELECT \"users\".* FROM \"users\") SELECT \"users\".* FROM \"users\"" 
```

**Comment by leoplct** [comment]
ok, It seems the issue it's caused by 
`gem 'resque'`
it works if I remove this gem.

**Comment by GeorgeKaraszi** [comment]
hmmm, I'm glad your problem is solved. But it brings up another question as to why that gem would affect this one 🤔.

**Comment by Samsinite** [comment]
I'm getting the same error as well, don't have resque installed (we use sidedkiq).

**Comment by Samsinite** [comment]
@GeorgeKaraszi could it be due to how active record extended is being mixed into active record? What if it used the `ActiveSupport.on_load :active_record do ... end` hook to extend the functionality similar to how kaminari does it (https://github.com/kaminari/kaminari/blob/cd8601cc42b67267c15a13174bc2fc9bd5de1032/kaminari-activerecord/lib/kaminari/activerecord.rb).

**Comment by Samsinite** [comment]
I also do not see it in the `ActiveRecord::Base.ancestors` chain, or anything inheriting from `ActiveRecord::Base`, so I'm pretty sure the issue is how it is being included into `ActiveRecord::Base`.

**Comment by leoplct** [comment]
Any updates on this?
I have updated to 2.0 but still getting the same error

```
User.with(test: User.all)
NoMethodError (undefined method `with' for #<Class:0x00007fdf113a6ef0>)
```

**Comment by skyeagle** [comment]
I've found a workaround for now:

config/application.rb
```
require "rails/all"

require "active_record_extended"  # <-- add this before rails configuration 
```

thanks for the amazing gem!

**Comment by leoplct** [comment]
Great! This works for me too.

**Comment by pirj** [comment]
The gem [includes itself](https://github.com/GeorgeKaraszi/ActiveRecordExtended/blob/33000ed962205699768222e93179507d87c27f01/lib/active_record_extended/query_methods/unionize.rb#L249):
```ruby
ActiveRecord::Relation.prepend(ActiveRecordExtended::QueryMethods::Unionize)
```

To my best knowledge, this is prone to load order errors. To be a good citizen, Railtie mechanism would better be used, e.g:
```ruby
ActiveSupport.on_load :active_record do
  ActiveRecord::Relation.prepend ActiveRecordExtended::QueryMethods::Unionize
end
```
See [example](https://github.com/brendon/acts_as_list/blob/d4732a4c772106564e924753aaf71acd176ab682/lib/acts_as_list/active_record/acts/active_record.rb#L3) and [doc](https://api.rubyonrails.org/classes/ActiveSupport/LazyLoadHooks.html#method-i-on_load).

Another lead that might reveal the mystery is one of the comments above:
```ruby
Item.where.any(field: 'text') # works
Profile.with(test: Profile.all) # doesn't work
```

Is it `ActiveRecord::Relation` that is the right one to extend?
```ruby
class C < ActiveRecord::Base
end
C.ancestors.include?(ActiveRecord::Relation)
=> false
```
🤔

**Comment by pirj** [comment]
Bump

**Comment by GeorgeKaraszi** [comment]
Made some significant changes to the gem's loading ability. I would suggest pulling the latest branch down to test if the recent changes has solved some of these lingering problems. I suspect this is a chicken or egg problem with what is getting loaded first.

**Comment by skyeagle** [comment]
> Made some significant changes to the gem's loading ability. I would suggest pulling the latest branch down to test if the recent changes has solved some of these lingering problems. I suspect this is a chicken or egg problem with what is getting loaded first.

I've tested the master branch, and it seems to be fixing the issue. Thank you for your excellent work on this gem!

**Comment by GeorgeKaraszi** [comment]
closing this issue since recent changes might have resolved this concern. Open a new issue if this persists.
